---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-wireguard-operator-io-v1alpha1-wireguard
  failurePolicy: Fail
  name: vwireguard-v1alpha1.kb.io
  rules:
  - apiGroups:
    - wireguard-operator.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - wireguards
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-wireguard-operator-io-v1alpha1-wireguardpeer
  failurePolicy: Fail
  name: vwireguardpeer-v1alpha1.kb.io
  rules:
  - apiGroups:
    - wireguard-operator.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - wireguardpeers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-wireguard-operator-io-v1alpha1-wireguardtrafficflow
  failurePolicy: Fail
  name: vwireguardtrafficflow-v1alpha1.kb.io
  rules:
  - apiGroups:
    - wireguard-operator.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - wireguardtrafficflows
  sideEffects: None
