---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - wireguard-operator.io
  resources:
  - wireguardpeers
  - wireguards
  - wireguardtrafficflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wireguard-operator.io
  resources:
  - wireguardpeers/finalizers
  - wireguards/finalizers
  - wireguardtrafficflows/finalizers
  verbs:
  - update
- apiGroups:
  - wireguard-operator.io
  resources:
  - wireguardpeers/status
  - wireguards/status
  - wireguardtrafficflows/status
  verbs:
  - get
  - patch
  - update
