/*
Copyright 2025 DenktMit eG and contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WireGuardPeerSpec defines a WireGuard peer configuration.
// Peers represent remote WireGuard endpoints that can connect to this instance.
// Each peer has a unique public key and set of allowed IP ranges.
type WireGuardPeerSpec struct {
	WireGuardReferenceSpec `json:",inline"`

	// +optional
	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9+/]{43}=$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="publicKey is immutable once set"

	// PublicKey identifies this peer uniquely in WireGuard.
	// Base64-encoded 32-byte key generated by wg genkey/pubkey.
	// This field is immutable once set to prevent connection disruption.
	// If not provided, operator can auto-generate a key pair.
	PublicKey *string `json:"publicKey,omitempty"`

	// +optional

	// AllowedIPs defines which IP ranges this peer can use as source.
	// Acts as both routing table entries and access control.
	// If not specified, an IP will be automatically assigned from the WireGuard's address range.
	// Examples: ["10.0.1.2/32"] for single host, ["10.0.2.0/24"] for subnet.
	// For site-to-site: Use the remote site's network ranges.
	// For road warriors: Typically a single /32 address per peer (auto-assigned if omitted).
	AllowedIPs IPNets `json:"allowedIPs,omitempty"`

	// +optional

	// Endpoint specifies how to reach this peer.
	// Format: "<hostname-or-ip>:<port>"
	// Examples: "vpn.example.com:51820", "203.0.113.1:51820"
	// If not set, peer must initiate the connection (common for road warriors).
	// Supports both static IPs and DNS names (resolved periodically).
	Endpoint string `json:"endpoint,omitempty"`

	// +optional

	// Mtu sets the Maximum Transmission Unit for this peer connection.
	// If specified, overrides the interface MTU for this peer's traffic.
	// Useful when peer is behind a connection with lower MTU.
	Mtu MTU `json:"mtu,omitempty"`

	// +optional
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=65535

	// PersistentKeepalive sends keepalive packets every N seconds.
	// Keeps NAT mappings and firewall states alive.
	// Common values:
	// - 0: Disabled (default) - for stable connections
	// - 25: Recommended for NAT traversal
	// - 10-60: Range for different NAT timeout scenarios
	PersistentKeepalive int32 `json:"persistentKeepalive,omitempty"`

	// +optional

	// PresharedKeySecret adds an additional layer of symmetric encryption.
	// Optional but recommended for quantum-resistant security.
	// The secret must contain a base64-encoded 32-byte key.
	// Generate with: wg genpsk
	PresharedKeySecret *PresharedKeySecretRef `json:"presharedKeySecret,omitempty"`

	// +optional

	// ConfigSecretRef specifies where to store the generated WireGuard config.
	// The operator creates/updates a secret with a complete wg.conf file.
	// This config can be used by WireGuard clients for connection.
	// If not set but peer has no publicKey, defaults to "<peer-name>-config".
	// The secret will contain:
	// - wg.conf: Complete WireGuard configuration
	// - privateKey: The peer's private key (if auto-generated)
	ConfigSecretRef *ConfigSecretRef `json:"configSecretRef,omitempty"`

	// +optional

	// PeerSelector includes additional peers in the generated config.
	// Selected WireGuardPeer resources are added as [Peer] sections.
	// Useful for mesh networks where peers need to know about each other.
	// The selector is evaluated in the same namespace.
	PeerSelector *metav1.LabelSelector `json:"peerSelector,omitempty"`

	// +optional

	// ConfigAllowedIPs adds extra AllowedIPs only to the generated config file.
	// These IPs are NOT added as kernel routes on the server side.
	// Use cases:
	// - Client-side routing for split tunneling
	// - Including default route (0.0.0.0/0) for full tunnel configs
	// - Adding routes the client needs but server doesn't route
	ConfigAllowedIPs IPNets `json:"configAllowedIPs,omitempty"`

	// +optional
	// +kubebuilder:default=false

	// GenerateConfig controls whether to generate a WireGuard configuration file.
	// When true, a config secret will be created/maintained even if keys are provided externally.
	// If privateKey is not available, placeholder text will be used in the config.
	// The config secret name defaults to "<peer-name>-config" unless ConfigSecretRef is set.
	GenerateConfig *bool `json:"generateConfig,omitempty"`
}

// WireGuardPeerStatus represents the current state and statistics of the peer.
type WireGuardPeerStatus struct {
	// +optional

	// Phase indicates the peer's current state:
	// - Pending: Peer is being configured
	// - Active: Peer is configured and can connect
	// - Failed: Configuration error occurred
	Phase Phase `json:"phase,omitempty"`

	// +optional

	// LastHandshakeTime shows when this peer last authenticated.
	// Updated after successful WireGuard handshake.
	// If never connected or stale (>180s), peer may be unreachable.
	LastHandshakeTime metav1.Time `json:"lastHandshakeTime,omitempty"`

	// +optional

	// TransferBytes tracks bandwidth usage for this peer.
	// Updated periodically from WireGuard statistics.
	// Useful for monitoring peer activity and data consumption.
	TransferBytes *TransferBytes `json:"transferBytes,omitempty"`

	// +optional

	// Conditions provide detailed status information:
	// - Ready: Peer is configured in WireGuard
	// - EndpointResolved: Endpoint hostname resolved successfully
	// - ConfigSecretCreated: Config secret generated (if requested)
	// - Reachable: Recent handshake indicates peer is online
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// TransferBytes tracks bandwidth usage statistics for a WireGuard peer.
type TransferBytes struct {
	// Received is the total bytes received from this peer.
	Received int64 `json:"received"`

	// Sent is the total bytes sent to this peer.
	Sent int64 `json:"sent"`

	// ReceiveHumanReadable shows received bytes in human format (e.g., "1.5 GiB").
	ReceiveHumanReadable string `json:"receiveHumanReadable"`

	// TransmitHumanReadable shows sent bytes in human format (e.g., "2.3 GiB").
	TransmitHumanReadable string `json:"transmitHumanReadable"`

	// TotalHumanReadable shows total transfer in human format (e.g., "3.8 GiB").
	TotalHumanReadable string `json:"totalHumanReadable"`
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:shortName=wgpeer
// +kubebuilder:subresource:status
// +kubebuilder:selectablefield:JSONPath=`.spec.wireguardRef.name`
// +kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase"
// +kubebuilder:printcolumn:name="Endpoint",type="string",JSONPath=".spec.endpoint"
// +kubebuilder:printcolumn:name="PublicKey",type="string",JSONPath=".spec.publicKey"
// +kubebuilder:printcolumn:name="AllowedIPs",type="string",JSONPath=".spec.allowedIPs[0]"
// +kubebuilder:printcolumn:name="LastHandshake",type="date",JSONPath=".status.lastHandshakeTime"
// +kubebuilder:printcolumn:name="Receive",type="string",JSONPath=".status.transferBytes.receiveHumanReadable"
// +kubebuilder:printcolumn:name="Transmit",type="string",JSONPath=".status.transferBytes.transmitHumanReadable"
// +kubebuilder:printcolumn:name="Total",type="string",JSONPath=".status.transferBytes.totalHumanReadable"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// WireGuardPeer represents a remote WireGuard endpoint configuration.
// Peers can be other sites (site-to-site VPN) or individual clients (road warriors).
type WireGuardPeer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   WireGuardPeerSpec   `json:"spec,omitempty"`
	Status WireGuardPeerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WireGuardPeerList contains a list of WireGuardPeer.
type WireGuardPeerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WireGuardPeer `json:"items"`
}

func init() {
	SchemeBuilder.Register(&WireGuardPeer{}, &WireGuardPeerList{})
}
