//go:build !ignore_autogenerated

/*
Copyright 2025 DenktMit eG and contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedEntity) DeepCopyInto(out *AppliedEntity) {
	*out = *in
	if in.ResolvedIPs != nil {
		in, out := &in.ResolvedIPs, &out.ResolvedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedEntity.
func (in *AppliedEntity) DeepCopy() *AppliedEntity {
	if in == nil {
		return nil
	}
	out := new(AppliedEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuthSpec)
		**out = **in
	}
	if in.RoleMappings != nil {
		in, out := &in.RoleMappings, &out.RoleMappings
		*out = make([]RoleMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthSpec) DeepCopyInto(out *BasicAuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthSpec.
func (in *BasicAuthSpec) DeepCopy() *BasicAuthSpec {
	if in == nil {
		return nil
	}
	out := new(BasicAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChainAssignment) DeepCopyInto(out *ChainAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChainAssignment.
func (in *ChainAssignment) DeepCopy() *ChainAssignment {
	if in == nil {
		return nil
	}
	out := new(ChainAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSecretRef) DeepCopyInto(out *ConfigSecretRef) {
	*out = *in
	out.SecretRefBase = in.SecretRefBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSecretRef.
func (in *ConfigSecretRef) DeepCopy() *ConfigSecretRef {
	if in == nil {
		return nil
	}
	out := new(ConfigSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterAction) DeepCopyInto(out *FilterAction) {
	*out = *in
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimitSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterAction.
func (in *FilterAction) DeepCopy() *FilterAction {
	if in == nil {
		return nil
	}
	out := new(FilterAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowRule) DeepCopyInto(out *FlowRule) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(FlowTrafficSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(FlowTrafficSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(FilterAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Transform != nil {
		in, out := &in.Transform, &out.Transform
		*out = new(TransformAction)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowRule.
func (in *FlowRule) DeepCopy() *FlowRule {
	if in == nil {
		return nil
	}
	out := new(FlowRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowTrafficSelector) DeepCopyInto(out *FlowTrafficSelector) {
	*out = *in
	if in.IPBlocks != nil {
		in, out := &in.IPBlocks, &out.IPBlocks
		*out = make(IPNets, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PeerSelector != nil {
		in, out := &in.PeerSelector, &out.PeerSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceSelector != nil {
		in, out := &in.ServiceSelector, &out.ServiceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make(InterfaceNames, len(*in))
		copy(*out, *in)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]PolicyPort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowTrafficSelector.
func (in *FlowTrafficSelector) DeepCopy() *FlowTrafficSelector {
	if in == nil {
		return nil
	}
	out := new(FlowTrafficSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IPNets) DeepCopyInto(out *IPNets) {
	{
		in := &in
		*out = make(IPNets, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPNets.
func (in IPNets) DeepCopy() IPNets {
	if in == nil {
		return nil
	}
	out := new(IPNets)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IPNetsRequired) DeepCopyInto(out *IPNetsRequired) {
	{
		in := &in
		*out = make(IPNetsRequired, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPNetsRequired.
func (in IPNetsRequired) DeepCopy() IPNetsRequired {
	if in == nil {
		return nil
	}
	out := new(IPNetsRequired)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in InterfaceAddresses) DeepCopyInto(out *InterfaceAddresses) {
	{
		in := &in
		*out = make(InterfaceAddresses, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceAddresses.
func (in InterfaceAddresses) DeepCopy() InterfaceAddresses {
	if in == nil {
		return nil
	}
	out := new(InterfaceAddresses)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in InterfaceNames) DeepCopyInto(out *InterfaceNames) {
	{
		in := &in
		*out = make(InterfaceNames, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceNames.
func (in InterfaceNames) DeepCopy() InterfaceNames {
	if in == nil {
		return nil
	}
	out := new(InterfaceNames)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCAuthSpec) DeepCopyInto(out *OIDCAuthSpec) {
	*out = *in
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(SecretRef)
		**out = **in
	}
	if in.JWTSecret != nil {
		in, out := &in.JWTSecret, &out.JWTSecret
		*out = new(SecretRef)
		**out = **in
	}
	if in.SessionMaxAge != nil {
		in, out := &in.SessionMaxAge, &out.SessionMaxAge
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCAuthSpec.
func (in *OIDCAuthSpec) DeepCopy() *OIDCAuthSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPort) DeepCopyInto(out *PolicyPort) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(Port)
		**out = **in
	}
	if in.EndPort != nil {
		in, out := &in.EndPort, &out.EndPort
		*out = new(Port)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPort.
func (in *PolicyPort) DeepCopy() *PolicyPort {
	if in == nil {
		return nil
	}
	out := new(PolicyPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresharedKeySecretRef) DeepCopyInto(out *PresharedKeySecretRef) {
	*out = *in
	out.SecretRefBase = in.SecretRefBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresharedKeySecretRef.
func (in *PresharedKeySecretRef) DeepCopy() *PresharedKeySecretRef {
	if in == nil {
		return nil
	}
	out := new(PresharedKeySecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateKeySecretRef) DeepCopyInto(out *PrivateKeySecretRef) {
	*out = *in
	out.SecretRefBase = in.SecretRefBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateKeySecretRef.
func (in *PrivateKeySecretRef) DeepCopy() *PrivateKeySecretRef {
	if in == nil {
		return nil
	}
	out := new(PrivateKeySecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitSpec) DeepCopyInto(out *RateLimitSpec) {
	*out = *in
	if in.Packets != nil {
		in, out := &in.Packets, &out.Packets
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Bytes != nil {
		in, out := &in.Bytes, &out.Bytes
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitSpec.
func (in *RateLimitSpec) DeepCopy() *RateLimitSpec {
	if in == nil {
		return nil
	}
	out := new(RateLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleMapping) DeepCopyInto(out *RoleMapping) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleMapping.
func (in *RoleMapping) DeepCopy() *RoleMapping {
	if in == nil {
		return nil
	}
	out := new(RoleMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
	out.SecretRefBase = in.SecretRefBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRefBase) DeepCopyInto(out *SecretRefBase) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRefBase.
func (in *SecretRefBase) DeepCopy() *SecretRefBase {
	if in == nil {
		return nil
	}
	out := new(SecretRefBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IPFamilies != nil {
		in, out := &in.IPFamilies, &out.IPFamilies
		*out = make([]corev1.IPFamily, len(*in))
		copy(*out, *in)
	}
	if in.IPFamilyPolicy != nil {
		in, out := &in.IPFamilyPolicy, &out.IPFamilyPolicy
		*out = new(corev1.IPFamilyPolicy)
		**out = **in
	}
	if in.InternalTrafficPolicy != nil {
		in, out := &in.InternalTrafficPolicy, &out.InternalTrafficPolicy
		*out = new(corev1.ServiceInternalTrafficPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferBytes) DeepCopyInto(out *TransferBytes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferBytes.
func (in *TransferBytes) DeepCopy() *TransferBytes {
	if in == nil {
		return nil
	}
	out := new(TransferBytes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformAction) DeepCopyInto(out *TransformAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformAction.
func (in *TransformAction) DeepCopy() *TransformAction {
	if in == nil {
		return nil
	}
	out := new(TransformAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIIngressSpec) DeepCopyInto(out *UIIngressSpec) {
	*out = *in
	if in.IngressClassName != nil {
		in, out := &in.IngressClassName, &out.IngressClassName
		*out = new(string)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]networkingv1.IngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIIngressSpec.
func (in *UIIngressSpec) DeepCopy() *UIIngressSpec {
	if in == nil {
		return nil
	}
	out := new(UIIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIServiceSpec) DeepCopyInto(out *UIServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIServiceSpec.
func (in *UIServiceSpec) DeepCopy() *UIServiceSpec {
	if in == nil {
		return nil
	}
	out := new(UIServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UISpec) DeepCopyInto(out *UISpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(UIServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(UIIngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UISpec.
func (in *UISpec) DeepCopy() *UISpec {
	if in == nil {
		return nil
	}
	out := new(UISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuard) DeepCopyInto(out *WireGuard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuard.
func (in *WireGuard) DeepCopy() *WireGuard {
	if in == nil {
		return nil
	}
	out := new(WireGuard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardList) DeepCopyInto(out *WireGuardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireGuard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardList.
func (in *WireGuardList) DeepCopy() *WireGuardList {
	if in == nil {
		return nil
	}
	out := new(WireGuardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardPeer) DeepCopyInto(out *WireGuardPeer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardPeer.
func (in *WireGuardPeer) DeepCopy() *WireGuardPeer {
	if in == nil {
		return nil
	}
	out := new(WireGuardPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardPeer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardPeerList) DeepCopyInto(out *WireGuardPeerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireGuardPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardPeerList.
func (in *WireGuardPeerList) DeepCopy() *WireGuardPeerList {
	if in == nil {
		return nil
	}
	out := new(WireGuardPeerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardPeerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardPeerSpec) DeepCopyInto(out *WireGuardPeerSpec) {
	*out = *in
	out.WireGuardReferenceSpec = in.WireGuardReferenceSpec
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = new(string)
		**out = **in
	}
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make(IPNets, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PresharedKeySecret != nil {
		in, out := &in.PresharedKeySecret, &out.PresharedKeySecret
		*out = new(PresharedKeySecretRef)
		**out = **in
	}
	if in.ConfigSecretRef != nil {
		in, out := &in.ConfigSecretRef, &out.ConfigSecretRef
		*out = new(ConfigSecretRef)
		**out = **in
	}
	if in.PeerSelector != nil {
		in, out := &in.PeerSelector, &out.PeerSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigAllowedIPs != nil {
		in, out := &in.ConfigAllowedIPs, &out.ConfigAllowedIPs
		*out = make(IPNets, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GenerateConfig != nil {
		in, out := &in.GenerateConfig, &out.GenerateConfig
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardPeerSpec.
func (in *WireGuardPeerSpec) DeepCopy() *WireGuardPeerSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardPeerStatus) DeepCopyInto(out *WireGuardPeerStatus) {
	*out = *in
	in.LastHandshakeTime.DeepCopyInto(&out.LastHandshakeTime)
	if in.TransferBytes != nil {
		in, out := &in.TransferBytes, &out.TransferBytes
		*out = new(TransferBytes)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardPeerStatus.
func (in *WireGuardPeerStatus) DeepCopy() *WireGuardPeerStatus {
	if in == nil {
		return nil
	}
	out := new(WireGuardPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardRef) DeepCopyInto(out *WireGuardRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardRef.
func (in *WireGuardRef) DeepCopy() *WireGuardRef {
	if in == nil {
		return nil
	}
	out := new(WireGuardRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardReferenceSpec) DeepCopyInto(out *WireGuardReferenceSpec) {
	*out = *in
	out.WireGuardRef = in.WireGuardRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardReferenceSpec.
func (in *WireGuardReferenceSpec) DeepCopy() *WireGuardReferenceSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardReferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardSpec) DeepCopyInto(out *WireGuardSpec) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make(InterfaceAddresses, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Dns != nil {
		in, out := &in.Dns, &out.Dns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrivateKeySecret != nil {
		in, out := &in.PrivateKeySecret, &out.PrivateKeySecret
		*out = new(PrivateKeySecretRef)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PeerSelector != nil {
		in, out := &in.PeerSelector, &out.PeerSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FwMark != nil {
		in, out := &in.FwMark, &out.FwMark
		*out = new(int32)
		**out = **in
	}
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(corev1.PodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(UISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardSpec.
func (in *WireGuardSpec) DeepCopy() *WireGuardSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardStatus) DeepCopyInto(out *WireGuardStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardStatus.
func (in *WireGuardStatus) DeepCopy() *WireGuardStatus {
	if in == nil {
		return nil
	}
	out := new(WireGuardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardTrafficFlow) DeepCopyInto(out *WireGuardTrafficFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardTrafficFlow.
func (in *WireGuardTrafficFlow) DeepCopy() *WireGuardTrafficFlow {
	if in == nil {
		return nil
	}
	out := new(WireGuardTrafficFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardTrafficFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardTrafficFlowList) DeepCopyInto(out *WireGuardTrafficFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WireGuardTrafficFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardTrafficFlowList.
func (in *WireGuardTrafficFlowList) DeepCopy() *WireGuardTrafficFlowList {
	if in == nil {
		return nil
	}
	out := new(WireGuardTrafficFlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WireGuardTrafficFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardTrafficFlowSpec) DeepCopyInto(out *WireGuardTrafficFlowSpec) {
	*out = *in
	out.WireGuardReferenceSpec = in.WireGuardReferenceSpec
	if in.Flows != nil {
		in, out := &in.Flows, &out.Flows
		*out = make([]FlowRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardTrafficFlowSpec.
func (in *WireGuardTrafficFlowSpec) DeepCopy() *WireGuardTrafficFlowSpec {
	if in == nil {
		return nil
	}
	out := new(WireGuardTrafficFlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardTrafficFlowStatus) DeepCopyInto(out *WireGuardTrafficFlowStatus) {
	*out = *in
	if in.ChainAssignments != nil {
		in, out := &in.ChainAssignments, &out.ChainAssignments
		*out = make([]ChainAssignment, len(*in))
		copy(*out, *in)
	}
	if in.AppliedTo != nil {
		in, out := &in.AppliedTo, &out.AppliedTo
		*out = make([]AppliedEntity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardTrafficFlowStatus.
func (in *WireGuardTrafficFlowStatus) DeepCopy() *WireGuardTrafficFlowStatus {
	if in == nil {
		return nil
	}
	out := new(WireGuardTrafficFlowStatus)
	in.DeepCopyInto(out)
	return out
}
