apiVersion: v2
name: wireguard-operator
description: WireGuard Operator provides a cloud-native approach to managing WireGuard VPN tunnels in Kubernetes environments.
type: application
version: 0.0.0
appVersion: v0.0.0
